# theme: jekyll-theme-slate
# theme: minimal-mistakes-jekyll
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
title: ""
description: ""
author: Steven Wu
email: stevenhwu@gmail.com
layout: page
# baseurl: "/stevenhwu.github.io"
url: "https://stevenhwu.github.io/"
permalink: pretty
google_analytics: G-JZ3H8R889L
fixed_navbar: top
hide_footer: true
# footer_menu: footer_menu
# hero_height: is-small


markdown: kramdown
highlighter: rouge
livereload: true

plugins:
- github-pages
- jekyll-sitemap  # auto generate sitemap
- jekyll-redirect-from


exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
