name: Jekyll site CI

on:
  push:
    branches: [ feature* ]
  pull_request:
    branches: [ feature* ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Dummy
        run: echo "dummy action"
    # - uses: actions/checkout@v2
    # - name: Build the site in the jekyll/builder container
    #   run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
